name: Upload

on:
  push:
    branches:
      - main

env:
  JFROG_NAMESPACE: "cloudops"
  JF_URL: ${{ secrets.JF_URL }}
  JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Modules
        run: npm install semantic-release @semantic-release/git @semantic-release/github -D
      - name: Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload:
    needs: release
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Format Terraform
        run: terraform fmt --recursive
      - name: Checkov GitHub Action
        continue-on-error: true
        uses: bridgecrewio/checkov-action@v12
        with:
          skip_check: CKV2_AWS_12,CKV2_AWS_11,CKV2_AWS_19
          output_format: cli,sarif
          output_file_path: console,results.sarif
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
      - name: Configure JFrog CLI
        run: |
          export SERVER_ID="wema"
          jf c add $SERVER_ID --url=$JF_URL --access-token=$JF_ACCESS_TOKEN --interactive=false
          jf tfc --server-id-deploy $SERVER_ID --repo-deploy terraform-local-modules
          jf tf p --namespace=${JFROG_NAMESPACE} --provider=local --tag=$(git describe --tags `git rev-list --tags --max-count=1`)
        working-directory: ./vpc
